name: docs
channels:
  - defaults
dependencies:
    # Base depends
  - python
  - pip
  
  - pdbfixer
  - openff-toolkit
  - openmmforcefields
  - cudatoolkit
  - numpy
  - requests

    # Pip-only installs
  #- pip:


