name: docs
channels:
  - defaults
dependencies:
    # Base depends
  - python
  - pip
  
  - pdbfixer
  - openff-toolkit
  - openmmforcefields
  - cudatoolkit


    # Pip-only installs
  #- pip:
    - numpy>=1.23.3
    - requests>=2.28.1
    - rdkit>=2022.03.5
    - mdtraj==1.9.7
    - cuda-python>=11.7.1
    - MDAnalysis>=2.3.0
    - pytest-shutil>=1.7.0
    - flask>=2.2.2

